-- 1. List the top 10 highest emitters of CO2 (excluding Land Use Change) from 1990 to 2020:

SELECT COUNTRY, ROUND(SUM(CO2),2) AS TOTAL_CO2_EMISSION
FROM EMISSIONS_DATA
WHERE YEAR BETWEEN 1990 AND 2020
GROUP BY COUNTRY
ORDER BY TOTAL_CO2_EMISSION DESC
LIMIT 10;

-- 2. List the 5 countries with the highest temperature change from the previous year in 2021:

SELECT COUNTRY, ROUND(TEMPERATURE_CHANGE_FROM_GHG,3) AS CHANGE_IN_TEMP
FROM EMISSIONS_DATA
WHERE YEAR = 2021
ORDER BY TEMPERATURE_CHANGE_FROM_GHG DESC
LIMIT 5;


-- 3. Write a SQL query to find the top 10 countries with the highest percentage increase in CO2 emissions from 2000 to 2020.

WITH EMISSIONS_CHANGE AS (
    SELECT COUNTRY,
        (SUM(CASE WHEN YEAR = 2020 THEN CO2 END) - SUM(CASE WHEN YEAR = 2000 THEN CO2 END)) AS CO2_EMISSION_CHANGE,
        SUM(CASE WHEN YEAR = 2000 THEN CO2 END) AS CO2_EMISSION_2000
    FROM EMISSIONS_DATA
    WHERE YEAR IN (2000, 2020)
    GROUP BY COUNTRY
)
SELECT COUNTRY, ROUND((CO2_EMISSION_CHANGE / CO2_EMISSION_2000) * 100,2) AS PERCENTAGE_INCREASE
FROM EMISSIONS_CHANGE
WHERE CO2_EMISSION_2000 != 0 AND CO2_EMISSION_2000 IS NOT NULL AND CO2_EMISSION_CHANGE IS NOT NULL
ORDER BY PERCENTAGE_INCREASE DESC
LIMIT 10;

-- 4. Identify the top 2 emitters of Nitrous Oxide and Methane per continent, along with their respective emission values. Provide the country name, emission gas type, and emission value for each selected country.

WITH EMISSIONS_PER_CONTINENT AS (
    SELECT CONTINENT, COUNTRY, SUM(NITROUS_OXIDE) AS TOTAL_NO_EMISSION, SUM(METHANE) AS TOTAL_METHANE_EMISSION
    FROM EMISSIONS_DATA
    GROUP BY CONTINENT, COUNTRY
)
SELECT CONTINENT,'NITROUS OXIDE' AS GAS,COUNTRY AS TOP_EMITTER,ROUND(TOTAL_NO_EMISSION,2) AS EMISSION_VALUE
FROM ( SELECT CONTINENT,COUNTRY,TOTAL_NO_EMISSION,
        ROW_NUMBER() OVER (PARTITION BY CONTINENT ORDER BY TOTAL_NO_EMISSION DESC) AS RN
    FROM EMISSIONS_PER_CONTINENT
) AS NO_RANKED_COUNTRIES
WHERE RN <= 2
UNION ALL
SELECT CONTINENT,'METHANE' AS GAS,COUNTRY AS TOP_EMITTER,ROUND(TOTAL_METHANE_EMISSION,2) AS EMISSION_VALUE
FROM ( SELECT CONTINENT,COUNTRY,TOTAL_METHANE_EMISSION,
        ROW_NUMBER() OVER (PARTITION BY CONTINENT ORDER BY TOTAL_METHANE_EMISSION DESC) AS RN
    FROM EMISSIONS_PER_CONTINENT
) AS METHANE_RANKED_COUNTRIES
WHERE RN <= 2;


-- 5. Identify the continents where the average temperature change exceeds the global average temperature change for each year between 2010 and 2020:

WITH GLOBAL_AVG_TEMP_CHANGE AS (
    SELECT YEAR, AVG(TEMPERATURE_CHANGE_FROM_GHG) AS GLOBAL_AVG_CHANGE
    FROM EMISSIONS_DATA
    WHERE YEAR BETWEEN 2010 AND 2020
    GROUP BY YEAR
),
CONTINENT_AVG_TEMP_CHANGE AS (
    SELECT YEAR, CONTINENT, AVG(TEMPERATURE_CHANGE_FROM_GHG) AS AVG_CHANGE
    FROM EMISSIONS_DATA
    WHERE YEAR BETWEEN 2010 AND 2020
    GROUP BY YEAR, CONTINENT
)
SELECT C.YEAR, C.CONTINENT, ROUND(C.AVG_CHANGE,5)
FROM CONTINENT_AVG_TEMP_CHANGE C
JOIN GLOBAL_AVG_TEMP_CHANGE G ON C.YEAR = G.YEAR
WHERE C.AVG_CHANGE > G.GLOBAL_AVG_CHANGE
ORDER BY C.YEAR DESC, C.AVG_CHANGE DESC, C.CONTINENT;
